import { Product, Category } from './types';

export const CATEGORIES: Category[] = [
  { id: '1', name: 'Insektisida', icon: 'Bug', color: '#fee2e2' },
  { id: '2', name: 'Fungisida', icon: 'Sprout', color: '#fef3c7' },
  { id: '3', name: 'Herbisida', icon: 'Scissors', color: '#dcfce7' },
  { id: '4', name: 'Pupuk', icon: 'Zap', color: '#dbeafe' },
  { id: '5', name: 'Benih', icon: 'Flower2', color: '#fed7aa' },
  { id: '6', name: 'Alat Tani', icon: 'Wrench', color: '#f2f2f2' },
];

export const MOCK_PRODUCTS: Product[] = [
  {
    id: 'p1',
    name: 'Terminator 500EC - Pembasmi Wereng',
    category: 'Insektisida',
    price: 85000,
    image: 'https://images.unsplash.com/photo-1576091160550-2173dba999ef?w=400&h=400&fit=crop',
    rating: 4.8,
    sold: 1250,
    location: 'Kab. Karawang',
    activeIngredient: 'BPMC 500g/l',
    form: 'Cair',
    regNumber: 'RI.01010120052345',
    sellerName: 'Tani Jaya Abadi',
    stock: 150,
    description: 'Insektisida racun kontak dan lambung berbentuk pekatan yang dapat diemulsikan, berwarna kuning kecoklatan untuk mengendalikan hama wereng coklat pada tanaman padi.'
  },
  {
    id: 'p2',
    name: 'GrowMore Leaf NPK 32-10-10',
    category: 'Pupuk',
    price: 45000,
    image: 'https://images.unsplash.com/photo-1559027615-cd2628902d4a?w=400&h=400&fit=crop',
    rating: 4.9,
    sold: 3400,
    location: 'Kota Surabaya',
    activeIngredient: 'Nitrogen 32%',
    form: 'Serbuk',
    regNumber: 'RI.02020220101234',
    sellerName: 'Surabaya Agro',
    stock: 500,
    description: 'Pupuk daun lengkap dalam bentuk kristal berwarna biru yang sangat mudah larut dalam air. Sangat baik untuk merangsang pertumbuhan vegetatif tanaman.'
  },
  {
    id: 'p3',
    name: 'Amistartop 325SC',
    category: 'Fungisida',
    price: 135000,
    image: 'https://images.unsplash.com/photo-1557804506-669714d2e9d8?w=400&h=400&fit=crop',
    rating: 5.0,
    sold: 890,
    location: 'Kab. Brebes',
    activeIngredient: 'Azoksistrobin 200g/l',
    form: 'Cair',
    regNumber: 'RI.01020120083211',
    sellerName: 'Berkah Tani',
    stock: 50,
    description: 'Fungisida sistemik yang bersifat protektif, kuratif, dan eradikatif berbentuk pekatan suspensi berwarna kuning muda.'
  },
  {
    id: 'p4',
    name: 'Roundup 486 SL 1 Liter',
    category: 'Herbisida',
    price: 98000,
    image: 'https://images.unsplash.com/photo-1559027615-cd2628902d4a?w=400&h=400&fit=crop',
    rating: 4.7,
    sold: 5000,
    location: 'Jakarta Barat',
    activeIngredient: 'Glifosat 486g/l',
    form: 'Cair',
    regNumber: 'RI.01030119941165',
    sellerName: 'Agro Official Store',
    stock: 1000,
    description: 'Herbisida purna tumbuh sistemik berbentuk larutan dalam air berwarna kuning keemasan, untuk mengendalikan alang-alang.'
  },
  {
    id: 'p5',
    name: 'Sprayer Elektrik 16L CBA',
    category: 'Alat Tani',
    price: 450000,
    image: 'https://images.unsplash.com/photo-1581092918056-0c4c3acd3789?w=400&h=400&fit=crop',
    rating: 4.6,
    sold: 210,
    location: 'Kab. Klaten',
    activeIngredient: '-',
    form: 'Granul',
    regNumber: 'SNI-8923-2020',
    sellerName: 'Mekanik Tani',
    stock: 25,
    description: 'Tangki semprot elektrik kapasitas 16 liter. Baterai tahan lama hingga 15 tangki sekali cas.'
  },
  {
    id: 'p6',
    name: 'Benih Jagung Hibrida BISI-18',
    category: 'Benih',
    price: 85000,
    image: 'https://images.unsplash.com/photo-1595433707802-6b2626ef1c91?w=400&h=400&fit=crop',
    rating: 4.9,
    sold: 1100,
    location: 'Kab. Kediri',
    activeIngredient: 'Benih Unggul',
    form: 'Granul',
    regNumber: 'KEPMENTAN 220/2021',
    sellerName: 'Benih Nasional',
    stock: 300,
    description: 'Benih jagung hibrida super, tongkol besar, rendemen tinggi, tahan bulai.'
  }
];
